{% set name = "osc-lib" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8f8a450fab2a1294e0aef8cdc9a255a1bcc5b58e1b2f6098e35e6db1e13e9d1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python >=3.6
    - setuptools
  run:
    - cliff >=3.2.0
    - keystoneauth1 >=3.14.0
    - openstacksdk >=0.15.0
    - oslo.i18n >=3.15.3
    - oslo.utils >=3.33.0
    - pbr
    - python >=3.6
    - setuptools
    - simplejson >=3.5.1
    - stevedore >=1.20.0

test:
  imports:
    - osc_lib

about:
  home: https://opendev.org/openstack/osc-lib
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: OpenStackClient Library
  doc_url: https://docs.openstack.org/osc-lib/latest/
  dev_url: https://opendev.org/openstack/osc-lib

extra:
  recipe-maintainers:
    - tschoonj
