{% set name = "osc-lib" %}
{% set version = "1.15.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a0a470f5f8f7c562a18719ffc2a9f0d98859b1666e920d93c99fbc32441797a5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pbr
    - pip
    - python
    - setuptools
  run:
    - babel
    - cliff
    - keystoneauth1
    - openstacksdk
    - oslo.i18n
    - oslo.utils
    - pbr
    - python
    - setuptools
    - simplejson
    - six
    - stevedore

test:
  imports:
    - osc_lib

about:
  home: https://opendev.org/openstack/osc-lib
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "OpenStackClient Library"
  doc_url: https://docs.openstack.org/osc-lib/latest/
  dev_url: https://opendev.org/openstack/osc-lib

extra:
  recipe-maintainers:
    - tschoonj
